#!/bin/bash

SCRIPT_DIR=`dirname $0`
BUILD_DIR=`dirname ${SCRIPT_DIR}`

SCRIPT=$1

# Source the config file
. ${BUILD_DIR}/config

# Download the image of necessary
${BUILD_ROOT}/scripts/download_image

# Prepare the image if necessary
LOOP=`${BUILD_ROOT}/scripts/mount_image`

# Just bring up a chrootshell if no script is specified
if [ -z "${SCRIPT}" ]; then
    echo "No script specified. Executing a chroot shell. Exit or ctrl-d to get out of the shell."
    chroot "${IMAGE_ROOT}"/ /usr/bin/qemu-arm-static /bin/bash
    echo "Shell closed."
elif [ "${SCRIPT}" == "-n" ]; then
    echo "No chroot (-n) specified. Just executing a shell. Exit or ctrl-d to get out of the shell."
    /bin/bash
    echo "Shell closed."
else
    # Does this script require chroot?
    if [[ "${SCRIPT}" == *"chroot"* ]]; then
	SCR=`basename "${SCRIPT}"`
	cp ${SCRIPT} ${IMAGE_ROOT}/tmp
	echo "Sourcing ${SCRIPT} in chroot"
	chroot "${IMAGE_ROOT}"/ /usr/bin/qemu-arm-static /usr/bin/env /tmp/${SCR}
	rm ${IMAGE_ROOT}/tmp/${SCR}
	echo "Completed ${SCRIPT}"
    else
	echo "Sourcing ${SCRIPT}"
	source ${SCRIPT}
	echo "Completed ${SCRIPT}"
    fi
fi

# Close the image
${BUILD_ROOT}/scripts/close_image ${LOOP}
