#!/bin/sh

set -e

apt-get install -y wget

if [ $# != 3 ]; then
    echo "Usage: <Qt version> <QOpenHD git URL> <QOpenHD branch>" 1>&2
    exit 1
fi
QTVER=$1
QOPENHD_REPO=$2
QOPENHD_BRANCH=$3

# Clone the cross-compiler repository
echo "Downloading raspberry pi tools"
if [ ! -d tools ]; then
    git clone https://github.com/raspberrypi/tools
fi

# Download the source tarball
echo "Downloading the Qt source tarball"
if [ ! -f qt-everywhere-src-${QTVER}.tar.xz ]; then
    wget https://download.qt.io/archive/qt/5.13/${QTVER}/single/qt-everywhere-src-${QTVER}.tar.xz
fi

# Extract the tarball
if [ -d qt-everywhere-src-${QTVER} ]; then
    rm -rf qt-everywhere-src-${QTVER}
fi
tar xf qt-everywhere-src-${QTVER}.tar.xz

# Build and install Qt Base
echo "Building Qt"
(
    cd qt-everywhere-src-${QTVER}
    ./configure \
	-release \
	-opengl es2 \
	-device linux-rasp-pi-g++ \
	-device-option CROSS_COMPILE=${WORKDIR}/tools/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian-x64/bin/arm-linux-gnueabihf- \
	-sysroot /opt/sysroot \
	-opensource \
	-confirm-license \
	-make libs \
	-prefix /opt/Qt/${QTVER} \
	-extprefix ${WORKDIR}/${QTVER} \
	-hostprefix ${WORKDIR}/host_tools \
	-v \
	-no-use-gold-linker \
	-force-pkg-config \
	-nomake examples \
	-no-compile-examples \
	-skip qtcharts \
	-skip qtdatavis3d \
	-skip qtwayland \
	-skip qtwebengine \
	-skip qtconnectivity \
	-skip qtxmlpatterns \
	-skip qtsensors \
	-skip qtpurchasing \
	-skip qtnetworkauth \
	-skip qtwebchannel \
	-skip qtwebsockets \
	-skip qtwebview \
	-no-feature-cups \
	-no-feature-testlib \
	-no-feature-dbus \
	-no-feature-vnc \
	-no-sql-sqlite \
	-no-compile-examples \
	-no-feature-xlib \
	-no-xcb \
	-qt-pcre \
	-no-pch \
	-evdev \
	-system-freetype \
	-glib
    make -j 4
    make install
)

# Build QOopenHD
echo "Building qopenhd"
git clone ${QOPENHD_REPO} -b ${QOPENHD_BRANCH}
(
    cd QOpenHD
    ${WORKDIR}/host_tools/bin/qmake
    make -j 4
)
